## <b>■ 복습</b>
    컴퓨터에게 사람의 말(자연어)을 이해시키기 위해서
        비교. CNN: 컴퓨터에게 이미지를 이해시키기 위해서
    
    2장. 개선된 통계기법 -> 단어의 분산표현 생성(밀집벡터) -> 단어와 단어 사이의 유사성
    3장. CBOW 신경망을 이용해서 문장을 학습 시킴 -> 단어의 분산 표현 생성(가중치)
    4장. CBOW 신경망에 큰 말뭉치가 입력될 수 있도록 개선
        CBOW 신경망의 문제점
            1. 말뭉치가 크면 메모리 사용량이 많다
            2. 성능이 느림
            
    5장. RNN 신경망 -> 기억하는 신경망
        실습
            작은 말뭉치                  --------> RNN 신경망에 입력하고 학습
            큰 말뭉치(스티브잡스 연설문)
                                  문장을 one hot 표현으로 변경
        RNN 신경망의 문제점(한계점)
            장기기억 취약
            기울기 소실 / 폭발
            
    6장. LSTM 신경망
        RNN과 LSTM 신경망의 차이가 무엇
            기억셀 존재
            게이트를 추가한 RNN LSTM
                forget
                input
                output
                새로운 기억
        기울기 소실 문제의 원인 : tanh 함수 -> relu함수
        기울기 폭발 문제의 원인 : matmul 연산 -> 게이트 이용해서 크기 조정
        LSTM 실습
            1. 긍정단어/부정단어를 컴퓨터가 인식할 수 있는지
            2. 주가예측을 LSTM 신경망으로 구현
            
    지금까지 배운 내용으로 생활에 필요한 것을 구현한다면
        주가예측 또는 시계열 데이터 분석
        
    책을 공부하는 방법
        RNN 원리를 책의 이론으로 배우고 실습은 keras로 구현
    
    7장. RNN을 사용해서 문장 생성 : 기사작성, 소설을 쓰는 AI 생성, 번역하는 신경망
        실습
            1. 영어 문장 생성
            2. 덧셈을 하는 신경망 구현
    8장. 어텐션 : 인공지능에게 질문을 하면 대답을 하는 것을 구현

#### ▩ 1. 7장의 큰 그림
    이번 7장은 6장에서 다룬 RNN 을 사용한 언어 모델을 쌀째 손질하여, 문장을 생성하는 기능을 구현합니다.
    그리고  seq2seq 에게 간단한 덧셈 문제를 학습시켜 구현합니다. seq2seq 는 encoder 와 decoder 를 연결한 모델로, 결국 2개의 RNN 을 조합한 단순한 구조입니다. 
    하지만 그 단순함에도 불구하고 seq2seq 는 매우 큰 가능성을 지니고 있어서 다양한 에플리케이션에 적용할 수 있습니다. 

#### ▩ 2. seq2seq 란 무엇인가요 ?
    seqeunce to sequence (시계열에서 시계열)를 뜻하는 말로 한 시계열 데이터를 다른 시계열 데이터로 변환하는 것

#### ▩ 3. seq2seq  구현은 어떻게 하나요 ? 
    RNN 2개를 연결하는 아주 간단한 방법으로 구현

#### ▩ 4. seq2seq  는 어디에 응용이 되나요 ?
    번역, 챗봇, 뉴스기사 자동 생성, 음성 인식 등에 다양하게 응용되어진다
                  ↓ 
             문장 자동 생성(7장)

#### ▩ 5. 5장에서 배웠던 RNN 신경망의 구조는 어떻게 되나요?
    You say goodbye and I say hello. 라는 말뭉치가 들어오면 특정 단어가 주어졌을 때 다음으로 나올 확률이 가장 높은 단어가 무엇인지를 예측하는 구조. 
    확률이 높은 단어는 선택되기 쉽고 확률이 낮은 단어는 선택되게 어려워지게끔 가중치가 생성되는 구조

![fig](http://cfile265.uf.daum.net/image/993A34455F543E9F1EDD39)
![fig2](http://cfile261.uf.daum.net/image/9943D5495F5440301FF6C8)

#### ▩ 6. 그런데 다르게 테스트를 하기 위해서 책에서 결정적이란 용어와 확률적이란 용어를 설명하면서 저자는 결정적인 방법으로 다음 단어를 선택하지 않고 확률적 방법으로 선택하겠다고 하는데 두 용어의 차이가 무엇입니까?
    결정적 : 결과가 예측 가능한 것. 기존에 배웠던 것처럼 특정 단어가 주어졌을 때 다음 단어를 예측 가능 확률이 가장 높은 단어를 선택하도록 하는 것
    확률적 : 결과가 확률에 따라 정해지는 것. 선택되는 단어는 실행할 때 마다 달라진다.
![fig](http://cfile281.uf.daum.net/image/99E3BC355F5442D620D53C)

    you say goodbye and i say hello. 라는 문장을 그대도 다 넣는게 아니라 
    I 다음에 나올 확률이 높은 say 를 그 다음 입력 단어로 넣고 say 를 입력한 후 다음 단어로 확률이 높은 단어가 hello 이므로 
    hello 가 다음 단어로 입력되어집니다. 

#### ▩ 7. 위와 같이 학습하면 어떤 효과가 있습니까 ?
    이렇게 생성된 문장은 훈련 데이터에 존재하지 않는 말. 말 그대로 새로 생성된 문장
    언어 모델은 훈련 데이터를 암기한 것이 아니라 훈련 데이터에서 사용된 단어의 패턴을 학습한 것이기 때문

#### ▩ 8. 문장 자동 생성을 영어 문장 자동 생성으로 테스트 해봅니다. 

In [1]:
# coding: utf-8
from dataset import ptb
"""
929_000개의 학습 단어, 73_000개의 validation 단어, 82_000개의 테스트 단어로 구성
예: 일기예보 기사를 자동으로 쓰는 AI를 만들고 싶다면 일기예보 기사의 용어(단어)가 들어있는 데이터 셋을 import 해야한다.
"""
from ch07.rnnlm_gen import RnnlmGen
"""
훈련 데이터의 문장을 암기하는 게 아니라 사용된 단어의 정렬 패턴을 학습하게 한 클래스
You say goodbye and I say hello.
"""
import sys

sys.path.append('..')

corpus, word_to_id, id_to_word = ptb.load_data('train')
vocab_size = len(word_to_id)
corpus_size = len(corpus)
print(vocab_size) # 10000
print(corpus_size) # 929589

10000
929589


In [2]:
model = RnnlmGen()
model.load_params('ch06/Rnnlm.pkl')

# start 문자와 skip 문자 설정
start_word = 'you'
start_id = word_to_id[start_word] # you의 단어 id를 추출
skip_words = ['N', '<unk>', '$'] # 샘플링 하지 않을 단어를 지정
skip_ids = [word_to_id[w] for w in skip_words] # 샘플링하지 않을 단어들의 단어 id를 추출

# 문장 생성
word_ids = model.generate(start_id, skip_ids)
txt = ' '.join([id_to_word[i] for i in word_ids])
txt = txt.replace(' <eos>', '.\n') # 한 문장의 끝을 나타내는 <eos> 표시 대신에 줄바꿈

print(txt)

you 'd see the woman 's meeting ownership under the proposed michigan mr. lawson.
 but it was sold.
 compared with an idea of both firms who i think i was down around my same time.
 he is interested as hollywood legislation high-interest capital because anthony technology inc. and services inc.
 mr. roman would be reached following the facility of the corporation for others.
 the chairman hopes yesterday as well as possible for period are tentatively priced for about half the institution would n't go share certificate and even if it was succeeded in the name


### ※ 문제. ch07/generate_better_text.py를 수행해서 이번에는 더 좋은 문장이 나오는지 테스트 하시오

In [3]:
# coding: utf-8
from dataset import ptb
from ch07.rnnlm_gen import BetterRnnlmGen
from common.np import *
import sys
sys.path.append('..')

corpus, word_to_id, id_to_word = ptb.load_data('train')
vocab_size = len(word_to_id)
corpus_size = len(corpus)


model = BetterRnnlmGen()
model.load_params('ch06/BetterRnnlm.pkl')

# start 문자와 skip 문자 설정
start_word = 'you'
start_id = word_to_id[start_word]
skip_words = ['N', '<unk>', '$']
skip_ids = [word_to_id[w] for w in skip_words]
# 문장 생성
word_ids = model.generate(start_id, skip_ids)
txt = ' '.join([id_to_word[i] for i in word_ids])
txt = txt.replace(' <eos>', '.\n')

print(txt)

model.reset_state()

start_words = 'the meaning of life is'
start_ids = [word_to_id[w] for w in start_words.split(' ')]

for x in start_ids[:-1]:
    x = np.array(x).reshape(1, 1)
    model.predict(x)

word_ids = model.generate(start_ids[-1], skip_ids)
word_ids = start_ids[:-1] + word_ids
txt = ' '.join([id_to_word[i] for i in word_ids])
txt = txt.replace(' <eos>', '.\n')
print('-' * 50)
print(txt)

OSError: No file: ch06\BetterRnnlm.pkl

### <b>[쉬움주의] 문장 자동 생성_한글_문제</b>

#### 문제1. 다음 text 의 문장을 단어와 단어 id 로 변환하시오 !
    text = 경마장에 있는 말이 뛰고 있다 그의 말이 법이다 가는 말이 고와야 오는 말이 곱다

In [1]:
from tensorflow.keras.utils import to_categorical
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences 
"""
문장마다 길이가 다르므로 패딩을 해서 일관된 문장 길이로 만들어주는 모듈
신경망에 배치처리를 하려면 일관된 사이즈로 문장을 만들어줘야 하기 때문에 필요
"""
from tensorflow.keras.preprocessing.text import Tokenizer # text를 숫자로 변환하는 모듈

text = """경마장에 있는 말이 뛰고 있다\n 그의 말이 법이다\n 가는 말이 고와야 오는 말이 곱다"""

t = Tokenizer() 
t.fit_on_texts([text]) # text 문자를 가지고 corpus, word_to_id, id_to_word를 생성
print(t.word_index)


{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


    [[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]

#### 문제2.  '경마장에 있는 말이 뛰고 있다'와 '그의 말이 법이다'와 '가는 말이 고와야 오는 말이 곱다'라는 세 가지 문장이 있다고 해봅시다. 모델이 문맥을 학습할 수 있도록 전체 문장의 앞의 단어들을 전부 고려하여 학습하도록 데이터를 재구성한다면 아래와 같이 총 11개의 샘플이 구성됩니다.  아래의 11개의 샘플을 아래와 같이 단어id로 출력되게 하시오 ! 

In [2]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])
    print(encoded)


[[2, 3, 1, 4, 5]]
[[6, 1, 7]]
[[8, 1, 9, 10, 1, 11]]


#### ※ 문제3. (점심시간 문제) 아래의 결과를 아래와 같이 출력되게 코드를 수정하시오
    [[2, 3, 1, 4, 5]]                             [2, 3, 1, 4, 5]
    [[6, 1, 7]]                       ->          [6, 1, 7]
    [[8, 1, 9, 10, 1, 11]]                        [8, 1, 9, 10, 1, 11]


In [3]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])
    for sent in encoded:
        print(sent)


[2, 3, 1, 4, 5]
[6, 1, 7]
[8, 1, 9, 10, 1, 11]


    문장 ---> 숫자로 변환 -----------> RNN 신경망
              자연어 데이터의 전처리

In [4]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    print(encoded)
    for i in range(1,len(encoded)):
        print(i)
        

[2, 3, 1, 4, 5]
1
2
3
4
[6, 1, 7]
1
2
[8, 1, 9, 10, 1, 11]
1
2
3
4
5


#### 문제. 위의 결과를 아래와 같이 출력되게 하시오
    [2, 3, 1, 4, 5]
    [2, 3]
    [2, 3, 1]
    [2, 3, 1, 4]
    [2, 3, 1, 4, 5]
    [6, 1, 7]
    [6, 1]
    [6, 1, 7]
    [8, 1, 9, 10, 1, 11]
    [8, 1]
    [8, 1, 9]
    [8, 1, 9, 10]
    [8, 1, 9, 10, 1]
    [8, 1, 9, 10, 1, 11]

In [5]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    print(encoded)
    for i in range(1,len(encoded)):
        sequence = encoded[:i+1]
        print(sequence)
        

[2, 3, 1, 4, 5]
[2, 3]
[2, 3, 1]
[2, 3, 1, 4]
[2, 3, 1, 4, 5]
[6, 1, 7]
[6, 1]
[6, 1, 7]
[8, 1, 9, 10, 1, 11]
[8, 1]
[8, 1, 9]
[8, 1, 9, 10]
[8, 1, 9, 10, 1]
[8, 1, 9, 10, 1, 11]


In [6]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
print(sequences)


[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


    자연어(사람의 말) ----------> RNN 신경망
                    데이터 전처리
                        1. Tokenizer() : 토큰화와 정수 인코딩(단어에 대한 인덱싱)을 위해 사용
                        2. pad_sequence() : 샘플의 길이를 동일하게 맞춰주기 위해 사용
                        3. to_categorical() : 라벨들을 원핫 표현으로 변경해주기 위해 사용
    
    위의 전처리의 상세 과정
http://cafe.daum.net/oracleoracle/Sedp/743

#### 문제3. 아래의 리스트안의 샘플 리스트 중에 가장 길이가 긴 샘플의 길이를 출력하시오
    [[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]

In [7]:
max_len = max(len(l) for l in sequences)
print(max_len)


6


#### 문제4. 아래의 리스트를 가장 긴 리스트를 기준으로 나머지 리스트를 0 으로 패딩하시오
    변경 전
    [[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]
    
    변경 후
    [[ 0  0  0  0  2  3]
     [ 0  0  0  2  3  1]
     [ 0  0  2  3  1  4]
     [ 0  2  3  1  4  5]
     [ 0  0  0  0  6  1]
     [ 0  0  0  6  1  7]
     [ 0  0  0  0  8  1]
     [ 0  0  0  8  1  9]
     [ 0  0  8  1  9 10]
     [ 0  8  1  9 10  1]
     [ 8  1  9 10  1 11]]

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences, maxlen=6, padding='pre')
print(sequences)


[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


#### 문제5. 아래의 리스트를 훈련 데이터와 훈련 데이터의 라벨로 구성하시오 !
    변경 전
    [[ 0  0  0  0  2  3]
     [ 0  0  0  2  3  1]
     [ 0  0  2  3  1  4]
     [ 0  2  3  1  4  5]
     [ 0  0  0  0  6  1]
     [ 0  0  0  6  1  7]
     [ 0  0  0  0  8  1]
     [ 0  0  0  8  1  9]
     [ 0  0  8  1  9 10]
     [ 0  8  1  9 10  1]
     [ 8  1  9 10  1 11]]

    변경 후
    [[ 0  0  0  0  2]
     [ 0  0  0  2  3]
     [ 0  0  2  3  1]
     [ 0  2  3  1  4]
     [ 0  0  0  0  6]
     [ 0  0  0  6  1]
     [ 0  0  0  0  8]
     [ 0  0  0  8  1]
     [ 0  0  8  1  9]
     [ 0  8  1  9 10]
     [ 8  1  9 10  1]]
     
     [ 3  1  4  5  1  7  1  9 10  1 11]

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
sequences = np.array(pad_sequences(sequences, maxlen=6, padding='pre'))
X = sequences[:,:-1]
y = sequences[:,-1]
X, y


(array([[ 0,  0,  0,  0,  2],
        [ 0,  0,  0,  2,  3],
        [ 0,  0,  2,  3,  1],
        [ 0,  2,  3,  1,  4],
        [ 0,  0,  0,  0,  6],
        [ 0,  0,  0,  6,  1],
        [ 0,  0,  0,  0,  8],
        [ 0,  0,  0,  8,  1],
        [ 0,  0,  8,  1,  9],
        [ 0,  8,  1,  9, 10],
        [ 8,  1,  9, 10,  1]]),
 array([ 3,  1,  4,  5,  1,  7,  1,  9, 10,  1, 11]))

#### 문제6. 라벨을 아래와 같이 원핫 표현으로 변경하시오 !
    변경 전:
    [ 3  1  4  5  1  7  1  9 10  1 11]

    변경 후:
    [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] # 3에 대한 원-핫 벡터
     [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] # 1에 대한 원-핫 벡터
     [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] # 4에 대한 원-핫 벡터
     [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] # 5에 대한 원-핫 벡터
     [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] # 1에 대한 원-핫 벡터
     [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] # 7에 대한 원-핫 벡터
     [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] # 1에 대한 원-핫 벡터
     [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] # 9에 대한 원-핫 벡터
     [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] # 10에 대한 원-핫 벡터
     [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] # 1에 대한 원-핫 벡터
     [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] # 11에 대한 원-핫 벡터

In [10]:
vocab_size = len(t.word_index) + 1
y = to_categorical(y, num_classes = vocab_size)
y


array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

#### ▩ 자연어 데이터를 위한 모델 구성
    Embedding() 관련 용어 설명
        단어를 원-핫 벡터로 만드는 과정을 원-핫 인코딩이라고 하였습니다. 
        이와 대비적으로 단어를 밀집 벡터로 만드는 작업을 워드 임베딩(word embedding)이라고 합니다. 
        밀집 벡터는 워드 임베딩 과정을 통해 나온 결과므로 임베딩 벡터(embedding vector)라고도 합니다.

    Embedding() : 
        Embedding()은 단어를 밀집 벡터로 만드는 역할을 합니다. 
        인공 신경망 용어로는 임베딩 층(embedding layer)을 만드는 역할을 합니다. 
        Embedding()은 정수 인코딩이 된 단어들을 입력을 받아서 임베딩을 수행합니다.
        Embedding()은 (number of samples, input_length)인 2D 정수 텐서를 입력받습니다. 
        이 때 각 sample은 정수 인코딩이 된 결과로, 정수의 시퀀스입니다. 
        Embedding()은 워드 임베딩 작업을 수행하고  3D 텐서를 리턴합니다.

    아래의 코드는 실제 동작되는 코드가 아니라 의사 코드(pseudo-code)로 임베딩의 개념 이해를 돕기 위해서 작성되었습니다.

#### 문제7.  위에서 만든 훈련 데이터 X 와 라벨 y 를 SimpleRNN 신경망에 입력하여 학습 시키시오 

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

vocab_size = len(t.word_index) + 1

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)


Train on 11 samples
Epoch 1/200
11/11 - 1s


InternalError: 2 root error(s) found.
  (0) Internal:  Blas GEMM launch failed : a.shape=(11, 32), b.shape=(32, 32), m=11, n=32, k=32
	 [[{{node sequential/simple_rnn/while/body/_1/MatMul_1}}]]
	 [[Reshape_7/_32]]
  (1) Internal:  Blas GEMM launch failed : a.shape=(11, 32), b.shape=(32, 32), m=11, n=32, k=32
	 [[{{node sequential/simple_rnn/while/body/_1/MatMul_1}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_1581]

Function call stack:
distributed_function -> distributed_function


#### 문제8. 다음의 함수를 이용해서 이제 입력된 단어로부터 다음 단어를 예측해서 문장을 생성하시오

In [ ]:
def sentence_generation(model, t, current_word, n):  # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word  # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n):  # n번 반복
        encoded = t.texts_to_sequences([current_word])[0]  # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5,
                                padding='pre')  # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)

    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items():
            if index == result:  # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break  # 해당 단어가 예측 단어이므로 break

        current_word = current_word + ' ' + word  # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word  # 예측 단어를 문장에 저장

    # for문이므로 이 행동을 다시 반복

    sentence = init_word + sentence
    return sentence

In [4]:
t = Tokenizer()
# '경마장에'를 시작 단어로 하고 그 뒤에 이어서 나오는 단어로 예측되는 단어를 4개 보여달라
print(sentence_generation(model, t, '경마장에', 4))
print(sentence_generation(model, t, '그의', 2))
print(sentence_generation(model, t, '가는', 4))

NameError: name 'Tokenizer' is not defined

In [ ]:
print(sentence_generation(model, t, '경마장에',4))

#### 문제9. 시작 단어를 다른 단어로 입력해보고 이어나 오는 예상 단어의 개수의 숫자를 더 크게 넣으시오

In [1]:
print(sentence_generation(model, t, '말이', 6))

NameError: name 'sentence_generation' is not defined